<div class="page-content"> 
	<div class="titolo-par">LA NOSTRA PASSIONE</div>
	<div class="testo-par">
	Bentornati !... a chi già ci faceva visita e ...
	</div>
	<div class="testo-par">
	Ben arrivati  !... ai nuovi amici che per la prima volta, incuriositi, si sono affacciati alla nostra 'finestra' virtuale.<br />Ci scusiamo innanzitutto per non essere stati molto presenti nell'ultimo anno, ma abbiamo avuto problemi tecnici legati all'aggiornamento del nostro sito. Inoltre, ad essere sinceri, non siamo molto abituati ad esternare per iscritto emozioni e sensazioni, preferiamo sicuramente condividere l'esperienza di un volo, di una giornata trascorsa insieme coltivando un hobby che per tanti di noi è qualcosa di più, una vera e propria <b>passione</b>.<br /> 
	Il nostro tempo libero, quello che ci rimane dopo esserci dedicati a famiglia ed amici, lo trascorriamo a progettare, costruire ed 'inventare' modelli di aerei, a discutere di
	<img class="alignleft" src="img/aliante.jpg" width="300" />
	motori, potenza, portanza, di venti e di termiche, ma soprattutto a <b>volare</b>.<br />
	Sul nostro campo di volo, in località Palaiola - Pieve di Compito, si sono avvicendati amici, semplici conoscenti e curiosi, appassionati ed esperti, campioni e dilettanti, tutti animati dall'amore per il volo, per la natura, per un hobby che fonda le sue radici in una ossessione-passione che l'uomo ha sempre visto come la massima espressione di libertà: <b>volare</b>.<br />Librarsi sopra tutto e tutti come un falco, una colomba o un gabbiano, farsi portare dal vento e scoprire così possibilità infinite di espressione, misurandosi solo con se stessi e l'ambiente naturale e grazie a questo inventare 'macchine volanti' in grado di dare sfogo e seguito al proprio mito.<br />Per tutto ciò ( ... e molto altro ancora!) ci ritroviamo insieme nei week-end con il naso all'insù, in cerca di cieli limpidi e di aerei impegnati in virtuosismi, l'orecchio attento alle minime variazioni del motore o al frusciare di venti 'favorevoli'.<br />Chi di Voi ha partecipato alle gare e agli eventi che annualmente organizziamo, avrà apprezzato la nostra struttura (la splendida pista del campo di volo, il grande gazebo sotto il quale ci riuniamo per preparare i nostri 'gioielli' o a mangiare tutti insieme, il grande parcheggio, la natura selvaggia ma al contempo "dolce" della nostra bella Toscana) e crediamo avrà potuto constatare con quanto amore e dedizione e passione ci occupiamo dell'organizzazione e dei nostri ospiti.<br />Vi invitiamo pertanto a venirci a trovare. Il viaggio varrà sicuramente la pena. Potrete volare, gareggiare, fare da semplici spettatori, goderVi le riproduzioni di aerei di ogni genere (alianti, biplani, acrobatici, a turbina, elettrici, d'epoca, innovativi) ed alimentare così una passione che a differenza di altre non consuma ma arricchisce ed appaga.<br />Seguiteci su questo nostro sito. Troverete notizie aggiornate sul meteo della nostra zona, sull'organizzazione di raduni o gare e su tutto quanto riguarda la nostra aviosuperficie.<br />Vi aspettiamo!...<br /><br /><b>Ognuno di noi ha un paio di ali, ma solo chi sogna impara a volare.</b><br />J. Morrison
	</div>
</div>
